import React, { useState } from 'react';
import { Image, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../src/api';
import { pickImage } from '../../src/picker';
import { Button, ConfirmDelete, DateText, ErrorState, Loading, Photo, styles, colors } from '../../src/ui';
import { TestForm } from '../(tabs)/tests';
export default function TestDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const isNew = id === 'new'; const numeric = Number(id); const query = useQuery({ queryKey: ['tests'], queryFn: api.tests, enabled: !isNew, select: items => items.find(item => item.id === numeric) }); const qc = useQueryClient(); const router = useRouter(); const [editing, setEditing] = useState(isNew); const [modalImage, setModalImage] = useState<string>();
  const upload = useMutation({ mutationFn: async ({ outcome, file }: { outcome?: number; file: Parameters<typeof api.uploadTest>[1] }) => outcome ? api.uploadOutcome(outcome, file) : api.uploadTest(numeric, file), onSuccess: value => { qc.invalidateQueries({ queryKey: ['tests'] }); qc.setQueryData(['tests'], (current: import('../../src/api').TestRecord[] | undefined) => current?.map(test => test.id === value.id ? value : test)); } });
  if (!isNew && query.isPending) return <Loading />; if (!isNew && query.isError) return <ErrorState message={(query.error as Error).message} retry={() => query.refetch()} />; if (!isNew && !query.data) return <ErrorState message="Test not found." retry={() => query.refetch()} />; if (editing) return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.title}>{isNew ? 'New test' : 'Edit test'}</Text><TestForm item={query.data} onDone={() => setEditing(false)} /></ScrollView>;
  const item = query.data!; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View><Text style={styles.title}>{item.title}</Text><DateText value={item.test_date} /></View><ConfirmDelete label="test" onConfirm={async () => { await api.deleteTest(numeric); qc.invalidateQueries({ queryKey: ['tests'] }); router.back(); }} /></View>{item.notes ? <Text style={[styles.muted, { marginVertical: 12 }]}>{item.notes}</Text> : null}<Button title="Edit test" onPress={() => setEditing(true)} secondary /><Text style={[styles.title, { fontSize: 20, marginTop: 22 }]}>Captures</Text>{item.outcomes.map(outcome => <View style={styles.card} key={outcome.id}><Text style={{ color: colors.ink, fontWeight: '800', marginBottom: 10 }}>{outcome.user.name}</Text><Photo path={outcome.image_path} size={150} /><Button title="Upload capture" onPress={async () => { const file = await pickImage(); if (file) upload.mutate({ outcome: outcome.id, file }); }} /></View>)}<Button title="Upload general image" onPress={async () => { const file = await pickImage(); if (file) upload.mutate({ file }); }} /><Modal visible={Boolean(modalImage)} transparent onRequestClose={() => setModalImage(undefined)}><Pressable style={{ flex: 1, backgroundColor: '#000c', justifyContent: 'center' }} onPress={() => setModalImage(undefined)}><Image source={{ uri: modalImage }} style={{ width: '100%', height: '80%', resizeMode: 'contain' }} /></Pressable></Modal></ScrollView>;
}
