import React, { useState } from 'react';
import { Image, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, imageUrl } from '../../src/api';
import type { Hotel, HotelRating } from '../../src/api';
import { pickImage } from '../../src/picker';
import { Button, ConfirmDelete, DateText, ErrorState, Field, Loading, Photo, RatingEditor, styles } from '../../src/ui';
export default function HotelDetail() {
 const { id } = useLocalSearchParams<{ id: string }>(); const isNew = id === 'new'; const numeric = Number(id); const query = useQuery({ queryKey: ['hotel', numeric], queryFn: () => api.hotel(numeric), enabled: !isNew });
 if (!isNew && query.isPending) return <Loading />; if (!isNew && query.isError) return <ErrorState message={(query.error as Error).message} retry={() => query.refetch()} />; return <HotelEditor id={numeric} isNew={isNew} item={query.data} />;
}
function HotelEditor({ id, isNew, item }: { id: number; isNew: boolean; item?: Hotel }) {
 const router = useRouter(); const qc = useQueryClient(); const users = useQuery({ queryKey: ['users'], queryFn: api.users }); const [name, setName] = useState(item?.name ?? ''); const [date, setDate] = useState(item?.visit_date ?? ''); const [location, setLocation] = useState(item?.location ?? ''); const [price, setPrice] = useState(item?.total_price == null ? '' : String(item.total_price)); const [currency, setCurrency] = useState<'UYU' | 'USD'>(item?.currency ?? 'UYU'); const [ratings, setRatings] = useState<HotelRating[]>(item?.ratings?.length === 2 ? item.ratings : (users.data ?? []).slice(0, 2).map(x => ({ user_id: x.id, score: 8, opinion: '' }))); const [error, setError] = useState(''); const [poster, setPoster] = useState(item?.image_path); const [modal, setModal] = useState(false);
 const save = useMutation({ mutationFn: () => { if (!name || !/^\d{4}-\d{2}-\d{2}$/.test(date) || ratings.length !== 2) throw new Error('Agrega un nombre, una fecha ISO (AAAA-MM-DD) y dos valoraciones.'); const payload = { name, visit_date: date, location: location || null, total_price: price === '' ? null : Number(price), currency: price === '' ? null : currency, ratings }; return isNew ? api.createHotel(payload) : api.updateHotel(id, payload); }, onSuccess: value => { qc.invalidateQueries({ queryKey: ['hotels'] }); qc.setQueryData(['hotel', value.id], value); router.replace(`/hotel/${value.id}`); }, onError: e => setError(e instanceof Error ? e.message : 'No se pudo guardar el hotel') });
 const upload = async () => { const file = await pickImage(); if (!file || isNew) return; const result = await api.uploadHotel(id, file); setPoster(result.image_path); qc.invalidateQueries({ queryKey: ['hotels'] }); };
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>{!isNew ? <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View><Text style={styles.title}>{name}</Text><DateText value={date} /></View><ConfirmDelete label="hotel" onConfirm={async () => { await api.deleteHotel(id); qc.invalidateQueries({ queryKey: ['hotels'] }); router.back(); }} /></View> : <Text style={styles.title}>Nuevo hotel</Text>}<Field label="Nombre" value={name} onChangeText={setName} /><Field label="Fecha de visita (AAAA-MM-DD)" value={date} onChangeText={setDate} /><Field label="Ubicación" value={location} onChangeText={setLocation} /><Field label="Precio total" value={price} onChangeText={setPrice} keyboardType="numeric" /><View style={{ flexDirection: 'row', marginBottom: 12 }}>{(['UYU', 'USD'] as const).map(value => <Pressable key={value} onPress={() => setCurrency(value)} style={[styles.chip, currency === value && styles.chipActive]}><Text style={[styles.chipText, currency === value && styles.chipTextActive]}>{value}</Text></Pressable>)}</View>{ratings.map((rating, index) => <RatingEditor key={rating.user_id} name={users.data?.find(x => x.id === rating.user_id)?.name ?? `Persona ${index + 1}`} score={rating.score} opinion={rating.opinion ?? ''} onScore={score => setRatings(current => current.map((x, i) => i === index ? { ...x, score } : x))} onOpinion={opinion => setRatings(current => current.map((x, i) => i === index ? { ...x, opinion } : x))} />)}{error ? <Text style={styles.error}>{error}</Text> : null}<Button title={save.isPending ? 'Guardando…' : 'Guardar hotel'} onPress={() => save.mutate()} disabled={save.isPending} />{!isNew ? <><Pressable onPress={() => poster && setModal(true)} style={{ alignSelf: 'center', marginTop: 18 }}><Photo path={poster} size={180} /></Pressable><Button title="Subir imagen del hotel" onPress={upload} secondary /></> : null}<Modal visible={modal} transparent onRequestClose={() => setModal(false)}><Pressable style={{ flex: 1, backgroundColor: '#000c', justifyContent: 'center' }} onPress={() => setModal(false)}><Image source={{ uri: poster ? imageUrl(poster) : undefined }} style={{ width: '100%', height: '80%', resizeMode: 'contain' }} /></Pressable></Modal></ScrollView>;
}
