import React, { useState } from 'react';
import { FlatList, Pressable, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { api, TestRecord } from '../../src/api';
import { Button, DateText, ErrorState, Field, Loading, Photo, styles, colors } from '../../src/ui';

export default function Tests() { const query = useQuery({ queryKey: ['tests'], queryFn: api.tests }); const router = useRouter(); if (query.isPending) return <Loading />; if (query.isError) return <ErrorState message="No se pudieron cargar los tests." retry={() => query.refetch()} />; return <FlatList data={query.data} keyExtractor={x => String(x.id)} style={styles.screen} contentContainerStyle={styles.content} refreshing={query.isRefetching} onRefresh={() => query.refetch()} ListHeaderComponent={<><Text style={styles.title}>Tests</Text><Text style={styles.subtitle}>Tus resultados y recuerdos compartidos.</Text><Button title="＋ Nuevo test" onPress={() => router.push('/test/new')} /></>} renderItem={({ item }) => <Pressable style={[styles.card, { flexDirection: 'row', gap: 13 }]} onPress={() => router.push(`/test/${item.id}`)}><Photo path={item.image_path} /><View><Text style={{ color: colors.ink, fontSize: 18, fontWeight: '800' }}>{item.title}</Text><DateText value={item.test_date} /><Text style={styles.muted}>{item.outcomes?.length ?? 0} capturas</Text></View></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.muted}>Aún no hay tests.</Text></View>} />; }
export function TestForm({ item, onDone }: { item?: TestRecord; onDone: (value: TestRecord) => void }) { const router = useRouter(); const qc = useQueryClient(); const users = useQuery({ queryKey: ['users'], queryFn: api.users }); const [title, setTitle] = useState(item?.title ?? ''); const [date, setDate] = useState(item?.test_date ?? ''); const [notes, setNotes] = useState(item?.notes ?? ''); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => { const ids = (users.data ?? []).slice(0, 2).map(x => x.id); if (!title || !/^\d{4}-\d{2}-\d{2}$/.test(date) || ids.length !== 2) throw new Error('Agrega un título, una fecha ISO (AAAA-MM-DD) y dos usuarios activos.'); return item ? api.updateTest(item.id, { title, test_date: date, notes: notes || null, outcomes: ids.map(user_id => ({ user_id })) }) : api.createTest({ title, test_date: date, notes: notes || null, outcomes: ids.map(user_id => ({ user_id })) }); }, onSuccess: value => { qc.invalidateQueries({ queryKey: ['tests'] }); onDone(value); router.replace(`/test/${value.id}`); }, onError: e => setError(e instanceof Error ? e.message : 'No se pudo guardar el test') }); return <View>{error ? <Text style={styles.error}>{error}</Text> : null}<Field label="Título" value={title} onChangeText={setTitle} /><Field label="Fecha del test (AAAA-MM-DD)" value={date} onChangeText={setDate} /><Field label="Notas" value={notes} onChangeText={setNotes} multiline /><Button title={mutation.isPending ? 'Guardando…' : 'Guardar test'} onPress={() => mutation.mutate()} disabled={mutation.isPending} /></View>; }
