import React from 'react';
import { ActivityIndicator, Alert, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { imageUrl } from './api';

export const colors = { ink: '#30231f', muted: '#7e6a62', cream: '#fff8f3', paper: '#ffffff', coral: '#df6f63', peach: '#f8dfd6', gold: '#d69a39', border: '#ecd9d0', danger: '#b94444', green: '#4f8a65' };
export const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.cream }, content: { padding: 18, paddingBottom: 36 }, title: { color: colors.ink, fontSize: 28, fontWeight: '800', marginBottom: 5 }, subtitle: { color: colors.muted, fontSize: 15, marginBottom: 18 }, card: { backgroundColor: colors.paper, borderRadius: 18, padding: 16, marginBottom: 13, borderWidth: 1, borderColor: colors.border, shadowColor: '#8e6e60', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 }, input: { backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.border, color: colors.ink, borderRadius: 12, padding: 13, fontSize: 16, marginBottom: 12 }, label: { color: colors.ink, fontWeight: '700', marginBottom: 6, marginTop: 7 }, button: { backgroundColor: colors.coral, paddingVertical: 14, borderRadius: 13, alignItems: 'center', marginTop: 8 }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 16 }, secondary: { backgroundColor: colors.peach }, secondaryText: { color: colors.coral }, row: { flexDirection: 'row', alignItems: 'center', gap: 9 }, error: { color: colors.danger, marginVertical: 9, lineHeight: 20 }, empty: { alignItems: 'center', paddingVertical: 45 }, muted: { color: colors.muted }, chip: { borderColor: colors.border, borderWidth: 1, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8, marginRight: 7 }, chipActive: { backgroundColor: colors.coral, borderColor: colors.coral }, chipText: { color: colors.muted, fontWeight: '700' }, chipTextActive: { color: '#fff' } });
export function Button({ title, onPress, secondary, disabled, color }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; color?: string }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.secondary, color && { backgroundColor: color }, disabled && { opacity: 0.5 }]}><Text style={[styles.buttonText, secondary && styles.secondaryText]}>{title}</Text></Pressable>; }
export function Field({ label, value, onChangeText, placeholder, secureTextEntry, keyboardType, multiline, autoCapitalize, autoCorrect, onSubmitEditing }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; secureTextEntry?: boolean; keyboardType?: 'default' | 'email-address' | 'numeric'; multiline?: boolean; autoCapitalize?: 'none' | 'sentences' | 'words' | 'characters'; autoCorrect?: boolean; onSubmitEditing?: () => void }) { return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#b29e95" secureTextEntry={secureTextEntry} keyboardType={keyboardType} multiline={multiline} autoCapitalize={autoCapitalize} autoCorrect={autoCorrect} onSubmitEditing={onSubmitEditing} style={[styles.input, multiline && { minHeight: 84, textAlignVertical: 'top' }]} /></View>; }
export function Stars({ score, onChange, large = false }: { score: number; onChange?: (score: number) => void; large?: boolean }) { return <View style={styles.row}>{[1, 2, 3, 4, 5].map(star => <Pressable key={star} disabled={!onChange} onPress={() => onChange?.(star * 2)}><Ionicons name={score >= star * 2 ? 'star' : score >= star * 2 - 1 ? 'star-half' : 'star-outline'} size={large ? 29 : 18} color={colors.gold} /></Pressable>)}</View>; }
export function RatingEditor({ name, score, opinion, onScore, onOpinion }: { name: string; score: number; opinion: string; onScore: (score: number) => void; onOpinion: (opinion: string) => void }) { return <View style={styles.card}><Text style={{ color: colors.ink, fontSize: 16, fontWeight: '800', marginBottom: 9 }}>{name}</Text><Stars score={score} onChange={onScore} /><TextInput value={opinion} onChangeText={onOpinion} placeholder="Opinion (optional)" placeholderTextColor="#b29e95" style={[styles.input, { marginTop: 10, marginBottom: 0 }]} /></View>; }
export function Photo({ path, size = 92 }: { path?: string | null; size?: number }) { return path ? <Image source={{ uri: imageUrl(path) }} style={{ width: size, height: size, borderRadius: 14, backgroundColor: colors.peach }} /> : <View style={{ width: size, height: size, borderRadius: 14, backgroundColor: colors.peach, alignItems: 'center', justifyContent: 'center' }}><Ionicons name="image-outline" size={27} color={colors.coral} /></View>; }
export function Loading() { return <View style={styles.empty}><ActivityIndicator color={colors.coral} size="large" /></View>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <View style={styles.empty}><Ionicons name="cloud-offline-outline" size={38} color={colors.coral} /><Text style={[styles.error, { textAlign: 'center' }]}>{message}</Text><Button title="Try again" onPress={retry} secondary /></View>; }
export function ConfirmDelete({ label, onConfirm }: { label: string; onConfirm: () => void }) { return <Pressable onPress={() => Alert.alert(`Delete ${label}?`, 'This cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: onConfirm }])}><Ionicons name="trash-outline" size={21} color={colors.danger} /></Pressable>; }
export function Refreshable({ children, refreshing, onRefresh }: { children: React.ReactNode; refreshing: boolean; onRefresh: () => void }) { return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.coral} />} contentContainerStyle={{ paddingBottom: 25 }}>{children}</ScrollView>; }
export function DateText({ value }: { value: string }) { const date = new Date(`${value}T00:00:00`); return <Text style={styles.muted}>{Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString('es-UY')}</Text>; }
export function formatISO(value: string) { const parts = value.trim().split(/[/-]/); if (parts.length !== 3) return value; if (parts[0].length === 4) return value; return `${parts[2]}-${parts[1].padStart(2, '0')}-${parts[0].padStart(2, '0')}`; }
export function dateDisplay(value: string) { const parts = value.split('-'); return parts.length === 3 ? `${parts[2]}/${parts[1]}/${parts[0]}` : value; }
