export const API_URL=(import.meta.env.VITE_API_URL||'http://localhost:8000/api/v1').replace(/\/$/,'');
export const API_ORIGIN=API_URL.replace(/\/api\/v1\/?$/,'');
export type User={id:number;name:string;email?:string;is_active?:boolean;is_admin?:boolean;must_change_password?:boolean};
export type Currency='UYU'|'USD';
export type PlaceCategory='lunch'|'snack'|'dinner';
export type Place={id:number;name:string;category?:PlaceCategory|null;visit_date:string;location?:string|null;notes?:string|null;image_path?:string|null;photos?:string[];currency?:Currency|null;average_rating?:number|null;place_average_rating?:number|null;dish_average_rating?:number|null;ratings?:Rating[];dishes?:Dish[]};
export type Dish={id:number;name:string;description?:string|null;visit_id:number;user_id:number;score:number;notes?:string|null;image_path?:string|null;dish_price?:string|number|null;drink_price?:string|number|null;dessert_price?:string|number|null};
export type Rating={id:number;score:number;comment?:string|null;user_id:number;visit_id:number};
export type TestOutcome={id:number;user_id:number;result?:string|null;image_path?:string|null};
export type TestRecord={id:number;title:string;test_date:string;notes?:string|null;outcomes?:TestOutcome[];result?:string|null;image_path?:string|null};
export type MediaType='series'|'movie';
export type MediaRating={id:number;user_id:number;score:number;opinion?:string|null};
export type MediaEntry={id:number;title:string;media_type:MediaType;watched_date:string;category?:string|null;image_path?:string|null;ratings:MediaRating[];average_rating?:number|null};
export type HotelRating={id:number;user_id:number;score:number;opinion?:string|null};
export type HotelVisit={id:number;name:string;visit_date:string;location?:string|null;image_path?:string|null;ratings:HotelRating[];average_rating?:number|null;total_price?:string|number|null;currency?:Currency|null};
const moneyDigits=(value:string)=>{const clean=value.trim().replace(/[^\d,.-]/g,'');if(!clean||!/[0-9]/.test(clean))return null;const sign=clean.startsWith('-')?'-':'';const unsigned=clean.replace(/^-/,''),separators=[...unsigned.matchAll(/[,.]/g)].map(m=>m.index??0);let whole=unsigned, fraction='';if(separators.length){const last=separators[separators.length-1],tail=unsigned.slice(last+1).replace(/[,.]/g,'');const decimal=separators.length>1||tail.length<=2;if(decimal){whole=unsigned.slice(0,last).replace(/[,.]/g,'');fraction=tail.padEnd(2,'0').slice(0,2)}else whole=unsigned.replace(/[,.]/g,'')}whole=whole.replace(/\D/g,'')||'0';return BigInt(`${sign==='-'?'-':''}${whole}${fraction}`)};
export function parseMoney(value:string|number|bigint|null|undefined):bigint|null{if(value==null||value==='')return null;return moneyDigits(String(value))};
export function moneyToApi(value:string|number|bigint|null|undefined):string|null{const cents=parseMoney(value);if(cents==null)return null;const sign=cents<0n?'-':'',abs=cents<0n?-cents:cents;return `${sign}${abs/100n}.${(abs%100n).toString().padStart(2,'0')}`};
export function formatMoney(value:string|number|bigint|null|undefined,currency:Currency|null|undefined):string|null{const cents=parseMoney(value);if(cents==null||!currency)return null;const sign=cents<0n?'-':'',abs=cents<0n?-cents:cents,whole=(abs/100n).toLocaleString('es-UY'),fraction=(abs%100n).toString().padStart(2,'0');return `${currency} ${sign}${whole},${fraction}`};
function formatApiError(detail:unknown,status:number){if(Array.isArray(detail))return detail.map(x=>typeof x==='object'&&x&&'msg' in x?String(x.msg):String(x)).join(' · ');if(detail&&typeof detail==='object'&&'msg' in detail)return String(detail.msg);return typeof detail==='string'?detail:`No se pudo completar la solicitud (${status})`}
export async function api<T>(path:string,options:RequestInit={}):Promise<T>{const token=localStorage.getItem('twogether_token');const headers=new Headers(options.headers);const login=path==='/auth/login';if(options.body&&!(options.body instanceof FormData)&&!headers.has('Content-Type')&&!login)headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const body=login&&typeof options.body==='string'?new URLSearchParams(Object.entries(JSON.parse(options.body)) as [string,string][]):options.body;const r=await fetch(`${API_URL}${path}`,{...options,headers,body});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(formatApiError(d.detail,r.status))}return r.status===204?undefined as T:r.json()}
export function imageUrl(path?:string|null){return path?(path.startsWith('http')?path:`${API_ORIGIN}/uploads/${path}`):undefined}
export const endpoints={places:'/places',place:(id:number)=>`/places/${id}`,placeUpload:(id:number)=>`/places/${id}/upload`,ratings:(id:number)=>`/places/${id}/ratings`,dishes:'/dishes',dish:(id:number)=>`/dishes/${id}`,dishUpload:(id:number)=>`/dishes/${id}/upload`,tests:'/tests',test:(id:number)=>`/tests/${id}`,testUpload:(id:number)=>`/tests/${id}/upload`,testOutcomeUpload:(testId:number,outcomeId:number)=>`/tests/${testId}/outcomes/${outcomeId}/upload`,completePlaces:'/places/complete',completeTests:'/tests/complete',media:'/media',mediaItem:(id:number)=>`/media/${id}`,mediaUpload:(id:number)=>`/media/${id}/upload`,hotels:'/hotels',hotel:(id:number)=>`/hotels/${id}`,hotelUpload:(id:number)=>`/hotels/${id}/upload`,users:'/users',userActive:(id:number)=>`/users/${id}/active`,forcePassword:(id:number)=>`/users/${id}/force-password-change`,changePassword:'/auth/change-password'};
export const updatePlaceComplete=(id:number,data:unknown)=>api<Place>(`/places/${id}/complete`,{method:'PUT',body:JSON.stringify(data)});
export const uploadPlaceImage=(id:number,file:File)=>{const body=new FormData();body.append('image',file);return api<Place>(endpoints.placeUpload(id),{method:'POST',body})};
export const uploadDishImage=(id:number,file:File)=>{const body=new FormData();body.append('image',file);return api<Dish>(endpoints.dishUpload(id),{method:'POST',body})};
export const createTest=(data:unknown)=>api<TestRecord>(endpoints.completeTests,{method:'POST',body:JSON.stringify(data)});
export const updateTest=(id:number,data:unknown)=>api<TestRecord>(`/tests/${id}/complete`,{method:'PUT',body:JSON.stringify(data)});
export const uploadTestOutcomeImage=(testId:number,outcomeId:number,file:File)=>{const body=new FormData();body.append('image',file);return api<TestRecord>(endpoints.testOutcomeUpload(testId,outcomeId),{method:'POST',body})};
export const createPlaceComplete=(data:unknown)=>api<Place>(endpoints.completePlaces,{method:'POST',body:JSON.stringify(data)});
